/* دستور الوحدة الثقافية — CHARTER OF CULTURAL UNITY — app.js */
/* Based on "Dustur Al-Wahdah" by Sheikh Mohammed al-Ghazali (1917-1996) */

const T = {
  ar: {
    appTitle: 'دستور الوحدة الثقافية',
    splashSub: 'نحو وحدة إسلامية قائمة على التنوع والتسامح',
    splashHint: 'اضغط للتخطي',
    sacredRef: 'سورة آل عمران ٣: ١٠٣',
    tabHome: 'الرئيسية', tabCards: 'البطاقات', tabReflections: 'تأملات',
    tabHabits: 'العادات', tabQuiz: 'اختبار', tabAbout: 'الكتاب',
    cardsTitle: 'بطاقات الوحدة الثقافية',
    cardsDesc: '٢٠ بطاقة من كتاب دستور الوحدة — كل بطاقة درس في بناء الأمة الواحدة',
    reflectionsTitle: 'تأملات في الوحدة',
    reflectionsDesc: 'تأملات قرآنية في الوحدة والتنوع والتسامح بين المسلمين',
    habitsTitle: 'عاداتي اليومية', habitsDesc: 'عادات تبني الوحدة — تتبّع تقدمك يومياً',
    quizTitle: 'اختبر فهمك', quizDesc: 'هل تفهم أسس الوحدة الإسلامية؟',
    helpTitle: '❓ مساعدة', duaPanelTitle: '🤲 أدعية', resetBtn: 'إعادة تعيين اليوم',
    submitQuiz: 'اعرف النتيجة', dailyLabel: '✨ فكرة اليوم', quizAgain: 'أعد الاختبار',
    yes: 'نعم', no: 'لا', sometimes: 'أحياناً', share: 'مشاركة',
    searchPlaceholder: 'ابحث في البطاقات...', streakMsg: 'يوم متتالي!', allDone: 'أحسنت! أكملت جميع العادات!',
    splashFeatures: ['٢٠ بطاقة عن الوحدة الإسلامية','٦ تأملات قرآنية في التنوع والتسامح','عادات يومية لبناء الوحدة','اختبار ذاتي + أدعية'],
  },
  en: {
    appTitle: 'Charter of Cultural Unity',
    splashSub: 'Toward Islamic unity built on diversity and tolerance',
    splashHint: 'tap to skip',
    sacredRef: 'Surah Al-Imran 3:103',
    tabHome: 'Home', tabCards: 'Cards', tabReflections: 'Reflect',
    tabHabits: 'Habits', tabQuiz: 'Quiz', tabAbout: 'Book',
    cardsTitle: 'Cards of Cultural Unity',
    cardsDesc: '20 cards from the Charter of Unity — each card is a lesson in building one Ummah',
    reflectionsTitle: 'Reflections on Unity',
    reflectionsDesc: 'Quranic reflections on unity, diversity, and tolerance among Muslims',
    habitsTitle: 'My Daily Habits', habitsDesc: 'Unity-building habits — track your daily progress',
    quizTitle: 'Test Your Understanding', quizDesc: 'Do you understand the foundations of Islamic unity?',
    helpTitle: '❓ Help', duaPanelTitle: '🤲 Duas', resetBtn: 'Reset Today',
    submitQuiz: 'See Results', dailyLabel: '✨ Today\'s Insight', quizAgain: 'Retake Quiz',
    yes: 'Yes', no: 'No', sometimes: 'Sometimes', share: 'Share',
    searchPlaceholder: 'Search cards...', streakMsg: 'day streak!', allDone: 'Well done! All habits completed!',
    splashFeatures: ['20 cards on Islamic unity','6 Quranic reflections on diversity','Daily unity-building habits','Self-quiz + duas'],
  },
  fr: {
    appTitle: 'Charte de l\'Unite Culturelle',
    splashSub: 'Vers une unite islamique fondee sur la diversite et la tolerance',
    splashHint: 'appuyez pour passer',
    sacredRef: 'Sourate Al-Imran 3:103',
    tabHome: 'Accueil', tabCards: 'Cartes', tabReflections: 'Reflexion',
    tabHabits: 'Habitudes', tabQuiz: 'Quiz', tabAbout: 'Livre',
    cardsTitle: 'Cartes de l\'Unite Culturelle',
    cardsDesc: '20 cartes de la Charte de l\'Unite — chaque carte est une lecon pour construire une Oumma unie',
    reflectionsTitle: 'Reflexions sur l\'Unite',
    reflectionsDesc: 'Reflexions coraniques sur l\'unite, la diversite et la tolerance entre musulmans',
    habitsTitle: 'Mes Habitudes Quotidiennes', habitsDesc: 'Habitudes pour l\'unite — suivez vos progres',
    quizTitle: 'Testez Votre Comprehension', quizDesc: 'Comprenez-vous les fondements de l\'unite islamique ?',
    helpTitle: '❓ Aide', duaPanelTitle: '🤲 Duas', resetBtn: 'Reinitialiser',
    submitQuiz: 'Voir les Resultats', dailyLabel: '✨ Pensee du Jour', quizAgain: 'Refaire le Quiz',
    yes: 'Oui', no: 'Non', sometimes: 'Parfois', share: 'Partager',
    searchPlaceholder: 'Rechercher les cartes...', streakMsg: 'jours consecutifs !', allDone: 'Bravo ! Toutes les habitudes accomplies !',
    splashFeatures: ['20 cartes sur l\'unite islamique','6 reflexions coraniques sur la diversite','Habitudes quotidiennes pour l\'unite','Quiz + duas'],
  }
};

const CARDS = [
  {id:1,emoji:'🤝',ar:{title:'معنى الوحدة الثقافية',desc:'الوحدة الثقافية ليست توحيد الرأي بل توحيد الأصول والمبادئ مع احترام التنوع في الفروع. الأمة الواحدة تتسع للجميع.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'تعرف على مذهب مختلف عن مذهبك — ابحث عن نقاط الاتفاق'},en:{title:'The Meaning of Cultural Unity',desc:'Cultural unity is not uniformity of opinion but unity of principles while respecting diversity in details. One Ummah can accommodate everyone.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'Learn about a school of thought different from yours — look for common ground'},fr:{title:'Le Sens de l\'Unite Culturelle',desc:'L\'unite culturelle n\'est pas l\'uniformite d\'opinion mais l\'unite des principes tout en respectant la diversite dans les details.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'Decouvrez une ecole de pensee differente de la votre'}},
  {id:2,emoji:'📖',ar:{title:'القرآن دستور الوحدة',desc:'القرآن الكريم هو الدستور الجامع لكل المسلمين. لا فرق بين سني وشيعي في إيمانه بالقرآن. هو الأساس المشترك.',verse:'إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',action:'اقرأ آية اليوم وتأمل كيف تجمع المسلمين'},en:{title:'The Quran: Constitution of Unity',desc:'The Holy Quran is the unifying constitution for all Muslims. There is no difference in belief in the Quran. It is the common foundation.',verse:'إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',action:'Read a verse today and reflect on how it unites Muslims'},fr:{title:'Le Coran : Constitution de l\'Unite',desc:'Le Saint Coran est la constitution unificatrice de tous les musulmans. Il n\'y a pas de difference dans la croyance au Coran. C\'est le fondement commun.',verse:'إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',action:'Lisez un verset aujourd\'hui et reflechissez a comment il unit les musulmans'}},
  {id:3,emoji:'🕌',ar:{title:'أركان الإسلام تجمعنا',desc:'الشهادتان والصلاة والزكاة والصوم والحج — أركان متفق عليها بين جميع المسلمين بلا استثناء.',verse:'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',action:'صلِّ اليوم في مسجد لا تعتاد الصلاة فيه — الإسلام أوسع من جماعتك'},en:{title:'The Pillars of Islam Unite Us',desc:'The testimony of faith, prayer, charity, fasting, and pilgrimage — pillars agreed upon by all Muslims without exception.',verse:'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',action:'Pray today in a mosque you don\'t usually attend — Islam is bigger than your group'},fr:{title:'Les Piliers de l\'Islam Nous Unissent',desc:'L\'attestation de foi, la priere, l\'aumone, le jeune et le pelerinage — des piliers agrees par tous les musulmans sans exception.',verse:'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',action:'Priez aujourd\'hui dans une mosquee que vous ne frequentez pas habituellement'}},
  {id:4,emoji:'🌍',ar:{title:'التنوع في الفروع رحمة',desc:'اختلاف المذاهب الفقهية في الفروع ليس شراً بل رحمة. الاختلاف الفقهي يعطي مرونة للأمة ويناسب ظروف الزمان والمكان.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً',action:'عندما تسمع رأياً فقهياً مختلفاً، لا ترفضه فوراً — ابحث عن دليله'},en:{title:'Diversity in Details Is Mercy',desc:'Differences among jurisprudential schools in details are not evil but mercy. Jurisprudential diversity gives the Ummah flexibility for different times and places.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً',action:'When you hear a different juristic opinion, don\'t reject it immediately — look for its evidence'},fr:{title:'La Diversite dans les Details Est une Misericorde',desc:'Les differences entre ecoles juridiques dans les details ne sont pas un mal mais une misericorde. La diversite juridique donne a l\'Oumma de la flexibilite.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً',action:'Quand vous entendez un avis juridique different, ne le rejetez pas — cherchez sa preuve'}},
  {id:5,emoji:'⚔️',ar:{title:'خطر التعصب المذهبي',desc:'التعصب لمذهب بعينه يمزق الأمة ويحول المسلمين إلى فرق متناحرة. الولاء يجب أن يكون للإسلام لا لمذهب.',verse:'إِنَّ الَّذِينَ فَرَّقُوا دِينَهُمْ وَكَانُوا شِيَعًا لَّسْتَ مِنْهُمْ فِي شَيْءٍ',action:'راجع موقفك من المذاهب الأخرى — هل أنت منصف أم متعصب؟'},en:{title:'The Danger of Sectarian Fanaticism',desc:'Fanaticism for a specific school tears the Ummah apart and turns Muslims into warring factions. Loyalty must be to Islam, not to a school.',verse:'إِنَّ الَّذِينَ فَرَّقُوا دِينَهُمْ وَكَانُوا شِيَعًا لَّسْتَ مِنْهُمْ فِي شَيْءٍ',action:'Review your stance toward other schools — are you fair or fanatical?'},fr:{title:'Le Danger du Fanatisme Sectaire',desc:'Le fanatisme pour une ecole specifique dechire l\'Oumma et transforme les musulmans en factions rivales. La loyaute doit etre envers l\'Islam, pas une ecole.',verse:'إِنَّ الَّذِينَ فَرَّقُوا دِينَهُمْ وَكَانُوا شِيَعًا لَّسْتَ مِنْهُمْ فِي شَيْءٍ',action:'Revoyez votre position envers les autres ecoles — etes-vous equitable ou fanatique ?'}},
  {id:6,emoji:'🔗',ar:{title:'وحدة العقيدة',desc:'جميع المسلمين يؤمنون بالله وملائكته وكتبه ورسله واليوم الآخر والقدر. هذا الإيمان المشترك أقوى من أي خلاف فقهي.',verse:'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ',action:'ذكّر نفسك اليوم بأصول الإيمان المشتركة بين المسلمين'},en:{title:'Unity of Creed',desc:'All Muslims believe in God, His angels, books, messengers, the Last Day, and divine decree. This shared faith is stronger than any jurisprudential disagreement.',verse:'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ',action:'Remind yourself today of the shared foundations of faith among Muslims'},fr:{title:'Unite de la Croyance',desc:'Tous les musulmans croient en Dieu, Ses anges, Ses livres, Ses messagers, le Jour Dernier et le destin divin. Cette foi partagee est plus forte que tout desaccord juridique.',verse:'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ',action:'Rappelez-vous aujourd\'hui les fondements communs de la foi entre musulmans'}},
  {id:7,emoji:'💬',ar:{title:'أدب الاختلاف',desc:'الاختلاف في الرأي لا يفسد للود قضية. الأئمة الأربعة اختلفوا واحترم كل منهم الآخر. هذا هو الأدب الإسلامي.',verse:'وَجَادِلْهُم بِالَّتِي هِيَ أَحْسَنُ',action:'إذا اختلفت مع أحد اليوم، حاور بأدب واحترم رأيه'},en:{title:'The Etiquette of Disagreement',desc:'Differences of opinion should not ruin friendships. The four Imams disagreed yet respected each other. This is Islamic etiquette.',verse:'وَجَادِلْهُم بِالَّتِي هِيَ أَحْسَنُ',action:'If you disagree with someone today, discuss with courtesy and respect their opinion'},fr:{title:'L\'Etiquette du Desaccord',desc:'Les differences d\'opinion ne devraient pas ruiner les amities. Les quatre Imams etaient en desaccord mais se respectaient mutuellement.',verse:'وَجَادِلْهُم بِالَّتِي هِيَ أَحْسَنُ',action:'Si vous etes en desaccord avec quelqu\'un aujourd\'hui, discutez avec courtoisie'}},
  {id:8,emoji:'🏛️',ar:{title:'التراث الإسلامي المشترك',desc:'التراث العلمي والحضاري للأمة الإسلامية ملك لجميع المسلمين. لا يحق لفئة أن تحتكره أو تدّعي أنها وحدها تمثل الإسلام.',verse:'كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ',action:'اقرأ عن عالم إسلامي من مذهب أو بلد مختلف عنك'},en:{title:'Shared Islamic Heritage',desc:'The scientific and civilizational heritage of the Islamic Ummah belongs to all Muslims. No group has the right to monopolize it or claim it alone represents Islam.',verse:'كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ',action:'Read about an Islamic scholar from a different school or country than yours'},fr:{title:'Patrimoine Islamique Partage',desc:'Le patrimoine scientifique et civilisationnel de l\'Oumma islamique appartient a tous les musulmans. Aucun groupe n\'a le droit de le monopoliser.',verse:'كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ',action:'Lisez sur un savant islamique d\'une ecole ou d\'un pays different du votre'}},
  {id:9,emoji:'🛡️',ar:{title:'العدو المشترك',desc:'أعداء الأمة لا يفرقون بين سني وشيعي. التفرق يضعف الأمة ويجعلها لقمة سائغة. الوحدة قوة والتفرق ضعف.',verse:'وَلَا تَنَازَعُوا فَتَفْشَلُوا وَتَذْهَبَ رِيحُكُمْ',action:'بدلاً من انتقاد فئة إسلامية أخرى، وجّه طاقتك لمواجهة التحديات الحقيقية'},en:{title:'The Common Enemy',desc:'The Ummah\'s enemies do not distinguish between Sunni and Shia. Division weakens the Ummah. Unity is strength and division is weakness.',verse:'وَلَا تَنَازَعُوا فَتَفْشَلُوا وَتَذْهَبَ رِيحُكُمْ',action:'Instead of criticizing another Islamic group, direct your energy toward real challenges'},fr:{title:'L\'Ennemi Commun',desc:'Les ennemis de l\'Oumma ne font pas de difference entre Sunnite et Chiite. La division affaiblit l\'Oumma. L\'unite est force et la division est faiblesse.',verse:'وَلَا تَنَازَعُوا فَتَفْشَلُوا وَتَذْهَبَ رِيحُكُمْ',action:'Au lieu de critiquer un autre groupe islamique, dirigez votre energie vers les vrais defis'}},
  {id:10,emoji:'📚',ar:{title:'العلم يوحّد',desc:'العلم الصحيح يقرّب بين المسلمين. الجهل هو المصدر الأول للتعصب والانقسام. كلما زاد علمك اتسع أفقك.',verse:'هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ',action:'تعلم شيئاً جديداً اليوم عن الإسلام من مصدر موثوق'},en:{title:'Knowledge Unites',desc:'True knowledge brings Muslims closer. Ignorance is the primary source of fanaticism and division. The more you learn, the broader your horizons.',verse:'هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ',action:'Learn something new about Islam today from a trusted source'},fr:{title:'Le Savoir Unit',desc:'Le vrai savoir rapproche les musulmans. L\'ignorance est la source premiere du fanatisme et de la division. Plus vous apprenez, plus vos horizons s\'elargissent.',verse:'هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ',action:'Apprenez quelque chose de nouveau sur l\'Islam aujourd\'hui'}},
  {id:11,emoji:'🌐',ar:{title:'الإسلام دين عالمي',desc:'الإسلام ليس ملكاً لقومية أو عرق. هو دين عالمي يتسع لكل الثقافات واللغات. العربي والعجمي سواء في الإسلام.',verse:'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ',action:'تواصل مع مسلم من ثقافة مختلفة عن ثقافتك'},en:{title:'Islam Is a Global Religion',desc:'Islam does not belong to a nationality or race. It is a global religion that accommodates all cultures and languages. Arab and non-Arab are equal in Islam.',verse:'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ',action:'Connect with a Muslim from a different cultural background'},fr:{title:'L\'Islam Est une Religion Mondiale',desc:'L\'Islam n\'appartient pas a une nationalite ou une race. C\'est une religion mondiale qui accueille toutes les cultures et langues.',verse:'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ',action:'Connectez-vous avec un musulman d\'un contexte culturel different'}},
  {id:12,emoji:'⚖️',ar:{title:'العدل أساس الوحدة',desc:'لا وحدة بدون عدل. الظلم يفرّق الأمة ويولّد الكراهية. العدل يجمع القلوب حتى لو اختلفت العقول.',verse:'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ',action:'كن عادلاً في حكمك على الآخرين اليوم — حتى من تختلف معهم'},en:{title:'Justice Is the Foundation of Unity',desc:'There is no unity without justice. Oppression divides the Ummah and breeds hatred. Justice unites hearts even when minds differ.',verse:'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ',action:'Be just in your judgment of others today — even those you disagree with'},fr:{title:'La Justice Est le Fondement de l\'Unite',desc:'Il n\'y a pas d\'unite sans justice. L\'oppression divise l\'Oumma et engendre la haine. La justice unit les coeurs meme quand les esprits different.',verse:'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ',action:'Soyez juste dans votre jugement des autres aujourd\'hui'}},
  {id:13,emoji:'🤲',ar:{title:'الأخوة الإسلامية',desc:'المسلمون إخوة بنص القرآن. الأخوة الإسلامية أقوى من رابطة الدم والقومية واللغة.',verse:'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ',action:'اتصل بأخ مسلم لم تتواصل معه منذ فترة — جدد الأخوة'},en:{title:'Islamic Brotherhood',desc:'Muslims are brothers by the text of the Quran. Islamic brotherhood is stronger than bonds of blood, nationality, and language.',verse:'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ',action:'Call a Muslim brother you haven\'t contacted in a while — renew the brotherhood'},fr:{title:'La Fraternite Islamique',desc:'Les musulmans sont freres par le texte du Coran. La fraternite islamique est plus forte que les liens du sang, de la nationalite et de la langue.',verse:'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ',action:'Appelez un frere musulman que vous n\'avez pas contacte depuis longtemps'}},
  {id:14,emoji:'🎯',ar:{title:'أولويات الأمة',desc:'الأمة بحاجة لترتيب أولوياتها: محاربة الجهل والفقر والمرض أولى من الخلافات المذهبية. القضايا الكبرى تنتظر.',verse:'وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ',action:'فكر في قضية إسلامية كبرى يمكنك المساهمة فيها'},en:{title:'The Ummah\'s Priorities',desc:'The Ummah needs to prioritize: fighting ignorance, poverty, and disease is more important than sectarian disputes. Major issues await.',verse:'وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ',action:'Think of a major Islamic cause you can contribute to'},fr:{title:'Les Priorites de l\'Oumma',desc:'L\'Oumma doit prioriser : combattre l\'ignorance, la pauvrete et la maladie est plus important que les disputes sectaires.',verse:'وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ',action:'Pensez a une grande cause islamique a laquelle vous pouvez contribuer'}},
  {id:15,emoji:'🌱',ar:{title:'التجديد لا التبديل',desc:'الوحدة تحتاج تجديداً في الفهم لا تبديلاً في الدين. نحتاج فهماً معاصراً للنصوص مع الحفاظ على الثوابت.',verse:'ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ',action:'اقرأ تفسيراً معاصراً لآية من القرآن اليوم'},en:{title:'Renewal Not Replacement',desc:'Unity needs renewal in understanding, not replacement of religion. We need contemporary understanding of texts while preserving fundamentals.',verse:'ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ',action:'Read a contemporary interpretation of a Quranic verse today'},fr:{title:'Renouveau et Non Remplacement',desc:'L\'unite necessite un renouveau dans la comprehension, pas un remplacement de la religion. Nous avons besoin d\'une comprehension contemporaine des textes.',verse:'ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ',action:'Lisez une interpretation contemporaine d\'un verset coranique aujourd\'hui'}},
  {id:16,emoji:'🏫',ar:{title:'دور التعليم في الوحدة',desc:'المناهج التعليمية يجب أن تربي على احترام التنوع لا التعصب. التعليم هو السلاح الأقوى لبناء أجيال موحدة.',verse:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',action:'علّم طفلاً اليوم قيمة احترام الاختلاف'},en:{title:'Education\'s Role in Unity',desc:'Educational curricula should teach respect for diversity, not fanaticism. Education is the strongest weapon for building united generations.',verse:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',action:'Teach a child today the value of respecting differences'},fr:{title:'Le Role de l\'Education dans l\'Unite',desc:'Les programmes educatifs doivent enseigner le respect de la diversite, pas le fanatisme. L\'education est l\'arme la plus forte pour construire des generations unies.',verse:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',action:'Enseignez a un enfant aujourd\'hui la valeur du respect des differences'}},
  {id:17,emoji:'💡',ar:{title:'الحوار لا الصدام',desc:'الحوار هو الطريق للوحدة. الصدام لا يولّد إلا العداوة. حاور من يختلف معك بعلم وأدب.',verse:'وَلَا تُجَادِلُوا أَهْلَ الْكِتَابِ إِلَّا بِالَّتِي هِيَ أَحْسَنُ',action:'حاور شخصاً يختلف معك في رأي فقهي — بأدب وعلم'},en:{title:'Dialogue Not Clash',desc:'Dialogue is the path to unity. Clashing only breeds enmity. Discuss with those who differ from you with knowledge and courtesy.',verse:'وَلَا تُجَادِلُوا أَهْلَ الْكِتَابِ إِلَّا بِالَّتِي هِيَ أَحْسَنُ',action:'Have a respectful dialogue with someone who holds a different juristic view'},fr:{title:'Dialogue et Non Affrontement',desc:'Le dialogue est le chemin vers l\'unite. L\'affrontement ne produit que l\'inimitie. Discutez avec ceux qui different de vous avec savoir et courtoisie.',verse:'وَلَا تُجَادِلُوا أَهْلَ الْكِتَابِ إِلَّا بِالَّتِي هِيَ أَحْسَنُ',action:'Ayez un dialogue respectueux avec quelqu\'un qui a un avis juridique different'}},
  {id:18,emoji:'❤️',ar:{title:'المحبة أساس الدين',desc:'المحبة في الله أساس الدين وأقوى رابطة بين المسلمين. من أحب أخاه في الله فقد بنى جسراً لا ينهدم.',verse:'لَا تَدْخُلُوا الْجَنَّةَ حَتَّىٰ تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّىٰ تَحَابُّوا',action:'عبّر عن محبتك لأخ مسلم اليوم — "إني أحبك في الله"'},en:{title:'Love Is the Foundation of Faith',desc:'Love for God\'s sake is the foundation of religion and the strongest bond between Muslims. Whoever loves their brother for God\'s sake has built an unbreakable bridge.',verse:'لَا تَدْخُلُوا الْجَنَّةَ حَتَّىٰ تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّىٰ تَحَابُّوا',action:'Express your love to a Muslim brother today — "I love you for God\'s sake"'},fr:{title:'L\'Amour Est le Fondement de la Foi',desc:'L\'amour en Dieu est le fondement de la religion et le lien le plus fort entre musulmans.',verse:'لَا تَدْخُلُوا الْجَنَّةَ حَتَّىٰ تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّىٰ تَحَابُّوا',action:'Exprimez votre amour a un frere musulman aujourd\'hui'}},
  {id:19,emoji:'🌍',ar:{title:'الأمة بين القومية والإسلام',desc:'القومية فرّقت المسلمين إلى دول متنافسة. الهوية الإسلامية أعلى من كل هوية قومية أو عرقية.',verse:'إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ',action:'لا تحكم على أحد بجنسيته أو لونه — احكم بتقواه'},en:{title:'The Ummah Between Nationalism and Islam',desc:'Nationalism has divided Muslims into competing states. Islamic identity is higher than any national or ethnic identity.',verse:'إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ',action:'Don\'t judge anyone by their nationality or color — judge by their piety'},fr:{title:'L\'Oumma entre Nationalisme et Islam',desc:'Le nationalisme a divise les musulmans en Etats concurrents. L\'identite islamique est superieure a toute identite nationale ou ethnique.',verse:'إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ',action:'Ne jugez personne par sa nationalite ou sa couleur — jugez par sa piete'}},
  {id:20,emoji:'🕌',ar:{title:'خاتمة: الوحدة فريضة',desc:'الوحدة ليست خياراً بل فريضة إسلامية. الله أمر بها والنبي ﷺ عمل من أجلها. كل مسلم مسؤول عن بناء الوحدة.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'ابدأ اليوم بخطوة واحدة نحو الوحدة — سامح، حاور، وتعلّم'},en:{title:'Conclusion: Unity Is an Obligation',desc:'Unity is not a choice but an Islamic obligation. God commanded it and the Prophet (peace be upon him) worked for it. Every Muslim is responsible for building unity.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'Start today with one step toward unity — forgive, dialogue, and learn'},fr:{title:'Conclusion : L\'Unite Est une Obligation',desc:'L\'unite n\'est pas un choix mais une obligation islamique. Dieu l\'a ordonnee et le Prophete (paix sur lui) a travaille pour elle.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',action:'Commencez aujourd\'hui par un pas vers l\'unite — pardonnez, dialoguez et apprenez'}}
];

const REFLECTIONS = [
  {emoji:'🤝',ar:{title:'لماذا تفرق المسلمون؟',question:'ما أسباب انقسام الأمة الإسلامية رغم وحدة الدين؟',answer:'التعصب المذهبي والجهل والأطماع السياسية فرّقت المسلمين. العلاج في العودة للقرآن والسنة بفهم واعٍ.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',verseRef:'آل عمران ٣: ١٠٣'},en:{title:'Why Did Muslims Divide?',question:'What caused the division of the Islamic Ummah despite the unity of religion?',answer:'Sectarian fanaticism, ignorance, and political ambitions divided Muslims. The cure is returning to the Quran and Sunnah with conscious understanding.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',verseRef:'Al-Imran 3:103'},fr:{title:'Pourquoi les Musulmans Se Sont-Ils Divises ?',question:'Qu\'est-ce qui a cause la division de l\'Oumma islamique malgre l\'unite de la religion ?',answer:'Le fanatisme sectaire, l\'ignorance et les ambitions politiques ont divise les musulmans. Le remede est le retour au Coran et a la Sunnah.',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',verseRef:'Al-Imran 3:103'}},
  {emoji:'📖',ar:{title:'كيف نبني الوحدة؟',question:'ما الخطوات العملية لبناء وحدة إسلامية حقيقية؟',answer:'العلم والحوار واحترام التنوع والتركيز على المشتركات. كل فرد يبدأ من نفسه ومجتمعه.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'الرعد ١٣: ١١'},en:{title:'How Do We Build Unity?',question:'What are practical steps to build genuine Islamic unity?',answer:'Knowledge, dialogue, respecting diversity, and focusing on commonalities. Every individual starts with themselves and their community.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'Ar-Ra\'d 13:11'},fr:{title:'Comment Construire l\'Unite ?',question:'Quelles sont les etapes pratiques pour construire une veritable unite islamique ?',answer:'Le savoir, le dialogue, le respect de la diversite et la focalisation sur les points communs. Chaque individu commence par lui-meme.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'Ar-Ra\'d 13:11'}},
  {emoji:'🌍',ar:{title:'هل التنوع ضعف أم قوة؟',question:'الأمة فيها مذاهب وثقافات ولغات مختلفة — هل هذا ضعف؟',answer:'التنوع قوة عظيمة إذا أُحسن إدارته. الأمة الإسلامية كالجسد الواحد — أعضاؤه مختلفة لكنها تعمل معاً.',verse:'وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا',verseRef:'الحجرات ٤٩: ١٣'},en:{title:'Is Diversity a Weakness or Strength?',question:'The Ummah has different schools, cultures, and languages — is this weakness?',answer:'Diversity is a great strength when managed well. The Islamic Ummah is like one body — its members differ but work together.',verse:'وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا',verseRef:'Al-Hujurat 49:13'},fr:{title:'La Diversite Est-Elle une Faiblesse ou une Force ?',question:'L\'Oumma a differentes ecoles, cultures et langues — est-ce une faiblesse ?',answer:'La diversite est une grande force quand elle est bien geree. L\'Oumma islamique est comme un seul corps — ses membres different mais travaillent ensemble.',verse:'وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا',verseRef:'Al-Hujurat 49:13'}},
  {emoji:'⚖️',ar:{title:'ما الفرق بين الاختلاف والانقسام؟',question:'هل كل اختلاف انقسام؟ وكيف نميز بينهما؟',answer:'الاختلاف في الفروع طبيعي ورحمة. الانقسام هو التعصب والتكفير والعداء. الأول يثري والثاني يدمر.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً وَلَا يَزَالُونَ مُخْتَلِفِينَ',verseRef:'هود ١١: ١١٨'},en:{title:'What Is the Difference Between Disagreement and Division?',question:'Is every disagreement a division? How do we distinguish them?',answer:'Disagreement in details is natural and merciful. Division is fanaticism, excommunication, and enmity. The former enriches while the latter destroys.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً وَلَا يَزَالُونَ مُخْتَلِفِينَ',verseRef:'Hud 11:118'},fr:{title:'Quelle Est la Difference entre Desaccord et Division ?',question:'Chaque desaccord est-il une division ? Comment les distinguer ?',answer:'Le desaccord dans les details est naturel et misericordieux. La division est le fanatisme, l\'excommunication et l\'hostilite.',verse:'وَلَوْ شَاءَ رَبُّكَ لَجَعَلَ النَّاسَ أُمَّةً وَاحِدَةً وَلَا يَزَالُونَ مُخْتَلِفِينَ',verseRef:'Hud 11:118'}},
  {emoji:'🕊️',ar:{title:'كيف تعامل النبي مع الاختلاف؟',question:'كيف أدار النبي ﷺ التنوع في المجتمع الإسلامي الأول؟',answer:'النبي ﷺ بنى مجتمعاً متنوعاً في المدينة — مهاجرين وأنصار وقبائل مختلفة. وحّدهم بالأخوة والعدل لا بالإكراه.',verse:'لَا إِكْرَاهَ فِي الدِّينِ',verseRef:'البقرة ٢: ٢٥٦'},en:{title:'How Did the Prophet Handle Differences?',question:'How did the Prophet manage diversity in the first Islamic society?',answer:'The Prophet built a diverse community in Medina — migrants, helpers, and different tribes. He united them through brotherhood and justice, not coercion.',verse:'لَا إِكْرَاهَ فِي الدِّينِ',verseRef:'Al-Baqarah 2:256'},fr:{title:'Comment le Prophete a-t-Il Gere les Differences ?',question:'Comment le Prophete a-t-il gere la diversite dans la premiere societe islamique ?',answer:'Le Prophete a construit une communaute diverse a Medine — emigres, aides et tribus differentes. Il les a unis par la fraternite et la justice, pas la coercition.',verse:'لَا إِكْرَاهَ فِي الدِّينِ',verseRef:'Al-Baqarah 2:256'}},
  {emoji:'🌟',ar:{title:'ما مسؤوليتي في بناء الوحدة؟',question:'ما الذي يمكنني فعله كفرد لتحقيق الوحدة الإسلامية؟',answer:'ابدأ بنفسك: تعلم، احترم الآخر، حاور بأدب، لا تتعصب، وسامح. التغيير يبدأ من الفرد.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'الرعد ١٣: ١١'},en:{title:'What Is My Responsibility in Building Unity?',question:'What can I do as an individual to achieve Islamic unity?',answer:'Start with yourself: learn, respect others, discuss with courtesy, don\'t be fanatical, and forgive. Change starts with the individual.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'Ar-Ra\'d 13:11'},fr:{title:'Quelle Est Ma Responsabilite dans la Construction de l\'Unite ?',question:'Que puis-je faire en tant qu\'individu pour realiser l\'unite islamique ?',answer:'Commencez par vous-meme : apprenez, respectez les autres, discutez avec courtoisie, ne soyez pas fanatique et pardonnez. Le changement commence par l\'individu.',verse:'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ',verseRef:'Ar-Ra\'d 13:11'}}
];

const HABITS = [
  {emoji:'🤝',ar:{label:'تواصل مع مسلم من ثقافة مختلفة',source:'بناء الوحدة'},en:{label:'Connect with a Muslim from a different culture',source:'Building unity'},fr:{label:'Connectez-vous avec un musulman d\'une culture differente',source:'Construire l\'unite'}},
  {emoji:'📖',ar:{label:'اقرأ صفحة من القرآن بتدبر',source:'القرآن دستور الوحدة'},en:{label:'Read a page of Quran with reflection',source:'Quran: constitution of unity'},fr:{label:'Lisez une page du Coran avec reflexion',source:'Coran : constitution de l\'unite'}},
  {emoji:'💬',ar:{label:'حاور من يختلف معك بأدب',source:'أدب الاختلاف'},en:{label:'Discuss respectfully with someone who disagrees',source:'Etiquette of disagreement'},fr:{label:'Discutez respectueusement avec quelqu\'un en desaccord',source:'Etiquette du desaccord'}},
  {emoji:'❤️',ar:{label:'عبّر عن محبتك لأخ مسلم',source:'الأخوة الإسلامية'},en:{label:'Express love to a Muslim brother',source:'Islamic brotherhood'},fr:{label:'Exprimez votre amour a un frere musulman',source:'Fraternite islamique'}},
  {emoji:'📚',ar:{label:'تعلم شيئاً عن مذهب آخر',source:'العلم يوحّد'},en:{label:'Learn about another school of thought',source:'Knowledge unites'},fr:{label:'Apprenez sur une autre ecole de pensee',source:'Le savoir unit'}},
  {emoji:'🤲',ar:{label:'ادعُ للأمة بالوحدة',source:'الدعاء سلاح المؤمن'},en:{label:'Pray for the Ummah\'s unity',source:'Dua is the believer\'s weapon'},fr:{label:'Priez pour l\'unite de l\'Oumma',source:'Le dua est l\'arme du croyant'}},
  {emoji:'⚖️',ar:{label:'كن عادلاً في حكمك على الآخرين',source:'العدل أساس الوحدة'},en:{label:'Be just in judging others',source:'Justice is the foundation'},fr:{label:'Soyez juste en jugeant les autres',source:'La justice est le fondement'}},
  {emoji:'🌱',ar:{label:'علّم طفلاً قيمة احترام الاختلاف',source:'التربية على الوحدة'},en:{label:'Teach a child the value of respecting differences',source:'Education for unity'},fr:{label:'Enseignez a un enfant le respect des differences',source:'Education pour l\'unite'}}
];

const QUIZ = [
  {ar:'هل تحترم المذاهب الإسلامية الأخرى؟',en:'Do you respect other Islamic schools of thought?',fr:'Respectez-vous les autres ecoles de pensee islamiques ?'},
  {ar:'هل تتعصب لمذهبك ضد المذاهب الأخرى؟',en:'Are you fanatical about your school against others?',fr:'Etes-vous fanatique de votre ecole contre les autres ?'},
  {ar:'هل تتعلم عن التنوع الإسلامي بانتظام؟',en:'Do you regularly learn about Islamic diversity?',fr:'Apprenez-vous regulierement sur la diversite islamique ?'},
  {ar:'هل تفرّق بين المسلمين على أساس القومية؟',en:'Do you differentiate between Muslims based on nationality?',fr:'Faites-vous une difference entre musulmans basee sur la nationalite ?'},
  {ar:'هل تحاور من يختلف معك بأدب؟',en:'Do you discuss courteously with those who disagree?',fr:'Discutez-vous avec courtoisie avec ceux qui sont en desaccord ?'},
  {ar:'هل تركز على المشتركات أم الخلافات؟',en:'Do you focus on commonalities or differences?',fr:'Vous concentrez-vous sur les points communs ou les differences ?'},
  {ar:'هل تدعو للوحدة في محيطك؟',en:'Do you advocate for unity in your circle?',fr:'Pronez-vous l\'unite dans votre entourage ?'},
  {ar:'هل تسامح من أساء إليك من المسلمين؟',en:'Do you forgive Muslims who wronged you?',fr:'Pardonnez-vous aux musulmans qui vous ont fait du tort ?'}
];

const DUAS = [
  {ar:{label:'دعاء الوحدة',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا',tr:'اللهم اجمع قلوب المسلمين'},en:{label:'Dua for Unity',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا',tr:'O God, unite our hearts and reconcile us'},fr:{label:'Dua pour l\'Unite',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا',tr:'O Dieu, unis nos coeurs et reconcilie-nous'}},
  {ar:{label:'دعاء الأخوة',text:'اللَّهُمَّ اجْعَلْنَا إِخْوَاناً مُتَحَابِّينَ فِيكَ',tr:'اللهم اجعلنا متحابين في الله'},en:{label:'Dua of Brotherhood',text:'اللَّهُمَّ اجْعَلْنَا إِخْوَاناً مُتَحَابِّينَ فِيكَ',tr:'O God, make us brothers who love one another for Your sake'},fr:{label:'Dua de Fraternite',text:'اللَّهُمَّ اجْعَلْنَا إِخْوَاناً مُتَحَابِّينَ فِيكَ',tr:'O Dieu, fais de nous des freres qui s\'aiment pour Ton amour'}},
  {ar:{label:'دعاء الهداية',text:'اللَّهُمَّ اهْدِنَا سَوَاءَ الصِّرَاطِ',tr:'ربي اهدنا الطريق المستقيم'},en:{label:'Dua for Guidance',text:'اللَّهُمَّ اهْدِنَا سَوَاءَ الصِّرَاطِ',tr:'O God, guide us to the straight path'},fr:{label:'Dua de Guidance',text:'اللَّهُمَّ اهْدِنَا سَوَاءَ الصِّرَاطِ',tr:'O Dieu, guide-nous vers le droit chemin'}},
  {ar:{label:'دعاء نصرة الأمة',text:'اللَّهُمَّ انصُرِ الْإِسْلَامَ وَالْمُسْلِمِينَ وَأَعِزَّ الْإِسْلَامَ وَالْمُسْلِمِينَ',tr:'ربي انصر الأمة ووحدها'},en:{label:'Dua for the Ummah',text:'اللَّهُمَّ انصُرِ الْإِسْلَامَ وَالْمُسْلِمِينَ وَأَعِزَّ الْإِسْلَامَ وَالْمُسْلِمِينَ',tr:'O God, support Islam and Muslims and honor Islam and Muslims'},fr:{label:'Dua pour l\'Oumma',text:'اللَّهُمَّ انصُرِ الْإِسْلَامَ وَالْمُسْلِمِينَ وَأَعِزَّ الْإِسْلَامَ وَالْمُسْلِمِينَ',tr:'O Dieu, soutiens l\'Islam et les musulmans et honore l\'Islam et les musulmans'}},
  {ar:{label:'دعاء التوفيق',text:'رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',tr:'ربنا ارزقنا رحمتك ورشدك'},en:{label:'Dua for Success',text:'رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',tr:'Our Lord, grant us mercy from You and guide us rightly'},fr:{label:'Dua pour le Succes',text:'رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',tr:'Notre Seigneur, accorde-nous Ta misericorde et guide-nous justement'}}
];

let lang = localStorage.getItem('dustur-lang') || 'ar';
let theme = localStorage.getItem('dustur-theme') || 'ocean';
const themes = ['ocean','night','sky'];
const themeIcons = ['🌊','🌙','☁️'];
const themeNames = {ocean:'Ocean / محيط',night:'Night / ليل',sky:'Sky / سماء'};
let currentCardIdx = -1;

document.addEventListener('DOMContentLoaded', () => {
  setTheme(theme); setLang(lang); initTabs(); initSplash(); initScrollTop();
  renderHome(); renderCards(); renderReflections(); renderHabits(); renderQuiz(); renderAbout(); renderHelp(); renderDuas();
  initScrollReveal(); initKeyboardNav();
});

function initSplash(){let c=5;const el=document.getElementById('splashCount');const f=document.getElementById('splashFeatures');if(f)f.innerHTML=T[lang].splashFeatures.map((x,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${x}</div>`).join('');const iv=setInterval(()=>{c--;if(el)el.textContent=c;if(c<=0){dismissSplash();clearInterval(iv)}},1000)}
function dismissSplash(){const s=document.getElementById('splash');if(s){s.classList.add('hidden');setTimeout(()=>s.style.display='none',500)}playSound('click')}

function setLang(l){lang=l;localStorage.setItem('dustur-lang',l);const rtl=l==='ar';document.documentElement.lang=l;document.documentElement.dir=rtl?'rtl':'ltr';document.body.dir=rtl?'rtl':'ltr';document.querySelectorAll('.lang-opt').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));const t=T[l];const s=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};s('appTitle',t.appTitle);s('splashSub',t.splashSub);s('splashHint',t.splashHint);s('tabHome',t.tabHome);s('tabCards',t.tabCards);s('tabReflections',t.tabReflections);s('tabHabits',t.tabHabits);s('tabQuiz',t.tabQuiz);s('tabAbout',t.tabAbout);s('cardsTitle',t.cardsTitle);s('cardsDesc',t.cardsDesc);s('reflectionsTitle',t.reflectionsTitle);s('reflectionsDesc',t.reflectionsDesc);s('habitsTitle',t.habitsTitle);s('habitsDesc',t.habitsDesc);s('quizTitle',t.quizTitle);s('quizDesc',t.quizDesc);s('helpTitle',t.helpTitle);s('duaPanelTitle',t.duaPanelTitle);s('habitsReset',t.resetBtn);renderHome();renderCards();renderReflections();renderHabits();renderQuiz();renderAbout();renderHelp();renderDuas();const f=document.getElementById('splashFeatures');if(f)f.innerHTML=T[l].splashFeatures.map((x,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${x}</div>`).join('')}

function setTheme(t){theme=t;document.documentElement.dataset.theme=t;localStorage.setItem('dustur-theme',t);const i=themes.indexOf(t);const e=document.getElementById('themeIcon');if(e)e.textContent=themeIcons[i]}
function cycleTheme(){const i=(themes.indexOf(theme)+1)%themes.length;setTheme(themes[i]);showToast(themeNames[themes[i]]);playSound('theme')}

function initTabs(){document.querySelectorAll('.tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');const p=document.getElementById('panel-'+tab.dataset.tab);if(p)p.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});playSound('click')})})}

function renderHome(){const t=T[lang];const d=new Date().getDate()%CARDS.length;const c=CARDS[d][lang];document.getElementById('dailyCard').innerHTML=`<div class="daily-label">${t.dailyLabel}</div><div class="daily-title">${c.title}</div><div class="daily-body">${c.desc}</div><div class="daily-action" onclick="document.querySelector('[data-tab=cards]').click()">${t.tabCards} &#8594;</div>`;const secs=[{icon:'🃏',tab:'cards',title:t.tabCards,desc:lang==='ar'?'٢٠ بطاقة عن الوحدة':lang==='fr'?'20 cartes sur l\'unite':'20 cards on unity'},{icon:'💭',tab:'reflections',title:t.tabReflections,desc:lang==='ar'?'تأملات في الوحدة':lang==='fr'?'Reflexions':'Reflections'},{icon:'📋',tab:'habits',title:t.tabHabits,desc:lang==='ar'?'تتبع يومي':lang==='fr'?'Suivi':'Tracking'},{icon:'🤔',tab:'quiz',title:t.tabQuiz,desc:lang==='ar'?'اختبر فهمك':lang==='fr'?'Testez-vous':'Test yourself'},{icon:'📖',tab:'about',title:t.tabAbout,desc:lang==='ar'?'عن الكتاب':lang==='fr'?'Le livre':'Book'}];document.getElementById('homeGrid').innerHTML=secs.map(s=>`<div class="home-card" onclick="document.querySelector('[data-tab=${s.tab}]').click()"><span class="hc-icon">${s.icon}</span><div class="hc-title">${s.title}</div><div class="hc-desc">${s.desc}</div></div>`).join('')}

function renderCards(){const t=T[lang];const sb=`<div class="search-bar"><input type="text" id="cardsSearch" class="search-input" placeholder="${t.searchPlaceholder}" oninput="filterCards(this.value)"><span class="search-icon">🔍</span></div>`;const cards=CARDS.map((c,i)=>{const d=c[lang];return`<div class="principle-card scroll-reveal" id="card-${c.id}" data-search="${d.title.toLowerCase()}"><div class="principle-head" onclick="toggleCard('card-${c.id}')"><span class="principle-num">${c.id}</span><span class="principle-emoji">${c.emoji}</span><span class="principle-title">${d.title}</span><span class="principle-chev">&#9660;</span></div><div class="principle-body"><div class="principle-inner"><p class="principle-desc">${d.desc}</p><div class="verse-box"><div class="verse-arabic">${d.verse}</div></div><div class="action-box"><span class="action-icon">💡</span><span>${d.action}</span></div><button class="share-btn" onclick="event.stopPropagation();shareCard(${i})"><span class="share-icon">&#128279;</span> ${t.share}</button></div></div></div>`}).join('');document.getElementById('cardsContainer').innerHTML=sb+cards}

function filterCards(q){q=q.toLowerCase().trim();document.querySelectorAll('.principle-card').forEach(c=>{const s=c.dataset.search||'';const t=c.querySelector('.principle-title');const tt=t?t.textContent.toLowerCase():'';c.style.display=(!q||s.includes(q)||tt.includes(q))?'':'none'})}

async function shareCard(i){const c=CARDS[i];const d=c[lang];const t=`${c.emoji} ${d.title}\n\n${d.desc}\n\n💡 ${d.action}\n\n— دستور الوحدة الثقافية`;if(navigator.share){try{await navigator.share({title:d.title,text:t})}catch(e){}}else{try{await navigator.clipboard.writeText(t);showToast(lang==='ar'?'تم النسخ!':lang==='fr'?'Copie !':'Copied!')}catch(e){showToast('Could not copy')}}}

function renderReflections(){const t=T[lang];document.getElementById('reflectionsContainer').innerHTML=REFLECTIONS.map(r=>{const d=r[lang];return`<div class="anxiety-card scroll-reveal"><div class="anxiety-header"><span class="anxiety-emoji">${r.emoji}</span><span class="anxiety-title">${d.title}</span></div><div class="anxiety-problem"><span class="anxiety-label">❓ ${lang==='ar'?'السؤال':lang==='fr'?'La Question':'The Question'}</span>${d.question}</div><div class="anxiety-solution"><span class="anxiety-label">💡 ${lang==='ar'?'الإجابة':lang==='fr'?'La Reponse':'The Answer'}</span>${d.answer}</div><div class="verse-box"><div class="verse-arabic">${d.verse}</div><div class="verse-ref">${d.verseRef}</div></div></div>`}).join('')}

function renderHabits(){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('dustur-habits')||'{}');if(hs.date!==today){updateStreak(hs);hs={date:today,done:[]};localStorage.setItem('dustur-habits',JSON.stringify(hs))}const streak=getStreak();const sh=streak>0?`<div class="streak-badge">🔥 ${streak} ${T[lang].streakMsg}</div>`:'';document.getElementById('habitsContainer').innerHTML=HABITS.map((h,i)=>{const d=h[lang];const done=hs.done.includes(i);return`<div class="habit-item ${done?'done':''}" onclick="toggleHabit(${i})"><span class="habit-check">${done?'&#10003;':''}</span><span class="habit-emoji">${h.emoji}</span><div><div class="habit-label">${d.label}</div><div class="habit-source">${d.source}</div></div></div>`}).join('');const se=document.getElementById('streakBadge');if(se)se.innerHTML=sh;updateHabitsProgress(hs)}

function toggleHabit(i){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('dustur-habits')||'{}');if(hs.date!==today)hs={date:today,done:[]};const idx=hs.done.indexOf(i);if(idx>-1)hs.done.splice(idx,1);else hs.done.push(i);localStorage.setItem('dustur-habits',JSON.stringify(hs));renderHabits();playSound(idx>-1?'click':'success');if(hs.done.length===HABITS.length){launchConfetti();showToast(T[lang].allDone)}}

function resetHabits(){localStorage.setItem('dustur-habits',JSON.stringify({date:new Date().toDateString(),done:[]}));renderHabits();showToast(lang==='ar'?'تم إعادة التعيين':lang==='fr'?'Reinitialise':'Reset')}
function updateHabitsProgress(hs){const d=hs.done.length,t=HABITS.length;const f=document.getElementById('habitsFill');const tx=document.getElementById('habitsText');if(f)f.style.width=(t>0?d/t*100:0)+'%';if(tx)tx.textContent=`${d}/${t}`}
function updateStreak(p){let s=JSON.parse(localStorage.getItem('dustur-streak')||'{"count":0,"lastDate":""}');if(p&&p.done&&p.done.length===HABITS.length&&p.date){const y=new Date();y.setDate(y.getDate()-1);if(p.date===y.toDateString())s.count++;else if(p.date!==new Date().toDateString())s.count=p.done.length===HABITS.length?1:0;s.lastDate=p.date}else if(p&&p.date){s.count=0;s.lastDate=p.date}localStorage.setItem('dustur-streak',JSON.stringify(s))}
function getStreak(){return JSON.parse(localStorage.getItem('dustur-streak')||'{"count":0}').count}

function launchConfetti(){const cv=document.getElementById('confettiCanvas');if(!cv)return;cv.style.display='block';const ctx=cv.getContext('2d');cv.width=window.innerWidth;cv.height=window.innerHeight;const ps=[];const cols=['#1565C0','#42A5F5','#90CAF9','#FFD54F','#66BB6A','#E57373','#B388FF'];for(let i=0;i<120;i++)ps.push({x:Math.random()*cv.width,y:Math.random()*cv.height-cv.height,w:Math.random()*10+5,h:Math.random()*6+3,color:cols[Math.floor(Math.random()*cols.length)],vx:(Math.random()-0.5)*4,vy:Math.random()*3+2,rot:Math.random()*360,rs:(Math.random()-0.5)*10});let f=0;function draw(){ctx.clearRect(0,0,cv.width,cv.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.rot+=p.rs;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=p.color;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore()});f++;if(f<120)requestAnimationFrame(draw);else{ctx.clearRect(0,0,cv.width,cv.height);cv.style.display='none'}}draw()}

function renderQuiz(){const t=T[lang];document.getElementById('quizContainer').innerHTML=QUIZ.map((q,i)=>`<div class="quiz-question scroll-reveal" id="quiz-q-${i}"><div class="quiz-q-text">${i+1}. ${q[lang]}</div><div class="quiz-options"><button class="quiz-opt" onclick="selectQuizOpt(${i},2)">${t.yes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},1)">${t.sometimes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},0)">${t.no}</button></div></div>`).join('')+`<button class="quiz-submit" onclick="submitQuiz()">${t.submitQuiz}</button>`;document.getElementById('quizResult').classList.add('hidden');window._quizAnswers={}}

function selectQuizOpt(qi,val){window._quizAnswers[qi]=val;document.querySelectorAll(`#quiz-q-${qi} .quiz-opt`).forEach((o,oi)=>o.classList.toggle('selected',[2,1,0][oi]===val));playSound('click')}

function submitQuiz(){const ans=window._quizAnswers||{};if(Object.keys(ans).length<QUIZ.length){showToast(lang==='ar'?'أجب على جميع الأسئلة':lang==='fr'?'Repondez a toutes les questions':'Answer all questions');return}const inv=[1,3];let sc=0;Object.entries(ans).forEach(([qi,v])=>{sc+=inv.includes(parseInt(qi))?(2-v):v});const mx=QUIZ.length*2;const pct=Math.round(sc/mx*100);let em,ti,de;if(pct>=75){em='🌟';ti=lang==='ar'?'ممتاز!':lang==='fr'?'Excellent !':'Excellent!';de=lang==='ar'?'فهمك لأسس الوحدة عميق!':lang==='fr'?'Votre comprehension est profonde !':'Your understanding is deep!'}else if(pct>=50){em='🤝';ti=lang==='ar'?'جيد':lang==='fr'?'Bien':'Good';de=lang==='ar'?'أنت على الطريق الصحيح.':lang==='fr'?'Vous etes sur la bonne voie.':'You\'re on the right track.'}else{em='📖';ti=lang==='ar'?'اقرأ المزيد':lang==='fr'?'Lisez plus':'Read More';de=lang==='ar'?'حان وقت التعلم عن الوحدة.':lang==='fr'?'Il est temps d\'apprendre sur l\'unite.':'Time to learn about unity.'}const r=document.getElementById('quizResult');r.classList.remove('hidden');r.innerHTML=`<div class="qr-emoji">${em}</div><div class="qr-score">${pct}%</div><div class="qr-title">${ti}</div><div class="qr-desc">${de}</div><button class="quiz-submit" onclick="renderQuiz()" style="margin-top:16px">${T[lang].quizAgain}</button>`;r.scrollIntoView({behavior:'smooth'});playSound('success')}

function renderAbout(){const a={ar:{dt:'⚠️ تنبيه مهم',d:'لست عالماً ولا مفتياً. هذا جهد متواضع من مسلم يحب كتب الشيخ الغزالي.',an:'الشيخ محمد الغزالي',ad:'١٩١٧ — ١٩٩٦',ab:'عالم ومفكر إسلامي مصري، لُقب بأديب الدعوة. ألّف أكثر من ٩٤ كتاباً.',bt:'عن الكتاب',bd:'كتاب "دستور الوحدة الثقافية بين المسلمين" يدعو لتوحيد الأمة الإسلامية على أساس القرآن والسنة مع احترام التنوع المذهبي والثقافي. يحارب التعصب ويبني جسور الحوار.',st:'المصادر',ss:['كتاب "دستور الوحدة الثقافية" — الشيخ محمد الغزالي','القرآن الكريم','صحيح البخاري ومسلم'],c:'تواصل: abdelhak.bourdim@gmail.com'},en:{dt:'⚠️ Important Notice',d:'I am not a scholar or mufti. This is a humble effort by a Muslim who loves Sheikh al-Ghazali\'s books.',an:'Sheikh Mohammed al-Ghazali',ad:'1917 — 1996',ab:'Egyptian Islamic scholar and thinker. Author of 94+ books. Known for fighting rigidity and building bridges of dialogue.',bt:'About the Book',bd:'"Charter of Cultural Unity Among Muslims" calls for unifying the Islamic Ummah based on Quran and Sunnah while respecting doctrinal and cultural diversity. It fights fanaticism and builds bridges of dialogue.',st:'Sources',ss:['"Dustur Al-Wahdah" by Sheikh Mohammed al-Ghazali','The Holy Quran','Sahih al-Bukhari and Muslim'],c:'Contact: abdelhak.bourdim@gmail.com'},fr:{dt:'⚠️ Avis Important',d:'Je ne suis ni savant ni mufti. C\'est un effort humble d\'un musulman qui aime les livres du Sheikh al-Ghazali.',an:'Sheikh Mohammed al-Ghazali',ad:'1917 — 1996',ab:'Savant et penseur islamique egyptien. Auteur de plus de 94 livres.',bt:'A Propos du Livre',bd:'La Charte de l\'Unite Culturelle entre Musulmans appelle a l\'unification de l\'Oumma islamique basee sur le Coran et la Sunnah tout en respectant la diversite doctrinale et culturelle.',st:'Sources',ss:['Dustur Al-Wahdah par Sheikh Mohammed al-Ghazali','Le Saint Coran','Sahih al-Bukhari et Muslim'],c:'Contact : abdelhak.bourdim@gmail.com'}}[lang];document.getElementById('aboutContainer').innerHTML=`<div class="about-disclaimer"><div class="about-disclaimer-title">${a.dt}</div><p>${a.d}</p></div><div class="about-author"><span class="about-author-icon">📚</span><div class="about-author-info"><div class="about-author-name">${a.an}</div><div class="about-author-dates">${a.ad}</div><div class="about-author-bio">${a.ab}</div></div></div><div class="about-section"><div class="about-section-title">${a.bt}</div><p class="about-text">${a.bd}</p></div><div class="about-section"><div class="about-section-title">${a.st}</div>${a.ss.map(s=>`<p class="about-text">&#8226; ${s}</p>`).join('')}</div><div class="about-section"><p class="about-text">${a.c}</p></div>`}

function renderHelp(){const h={ar:[{title:'⚠️ تنبيه',body:'لست عالماً. هذا جهد متواضع لنشر حكمة الشيخ الغزالي.'},{title:'📚 المصادر',body:'كتاب "دستور الوحدة الثقافية" للشيخ محمد الغزالي.'},{title:'✨ المميزات',body:'٣ لغات، ٣ أنماط، ٢٠ بطاقة، ٦ تأملات، تتبع عادات، اختبار، أدعية.'}],en:[{title:'⚠️ Disclaimer',body:'I am not a scholar. This is a humble effort to share Sheikh al-Ghazali\'s wisdom.'},{title:'📚 Sources',body:'"Charter of Cultural Unity" by Sheikh Mohammed al-Ghazali.'},{title:'✨ Features',body:'3 languages, 3 themes, 20 cards, 6 reflections, habit tracker, quiz, duas.'}],fr:[{title:'⚠️ Avertissement',body:'Je ne suis pas un savant. Effort humble pour partager la sagesse du Sheikh.'},{title:'📚 Sources',body:'Charte de l\'Unite Culturelle par Sheikh Mohammed al-Ghazali.'},{title:'✨ Fonctionnalites',body:'3 langues, 3 themes, 20 cartes, 6 reflexions, suivi habitudes, quiz, duas.'}]}[lang];document.getElementById('helpBody').innerHTML=h.map(x=>`<div class="help-item"><div class="help-item-title">${x.title}</div><div>${x.body}</div></div>`).join('')}

function renderDuas(){document.getElementById('duaPanelContent').innerHTML=DUAS.map(d=>{const dd=d[lang];return`<div class="dua-item"><div class="dua-item-label">${dd.label}</div><div class="dua-item-ar">${dd.text}</div><div class="dua-item-tr">${dd.tr}</div></div>`}).join('')}

function initScrollReveal(){if(!('IntersectionObserver' in window))return;const obs=new IntersectionObserver(e=>{e.forEach(en=>{if(en.isIntersecting){en.target.classList.add('revealed');obs.unobserve(en.target)}})},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});function o(){document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el=>obs.observe(el))}o();document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>setTimeout(o,100)))}

function initKeyboardNav(){document.addEventListener('keydown',e=>{if(e.key==='Escape'){const hp=document.getElementById('helpPanel');if(!hp.classList.contains('hidden')){toggleHelp();return}const dp=document.getElementById('duaPanel');if(!dp.classList.contains('hidden')){toggleDuaPanel();return}document.querySelectorAll('.principle-card.open').forEach(c=>c.classList.remove('open'))}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){const p=document.getElementById('panel-cards');if(!p||!p.classList.contains('active'))return;if(document.activeElement&&document.activeElement.id==='cardsSearch')return;e.preventDefault();const cards=Array.from(document.querySelectorAll('.principle-card')).filter(c=>c.style.display!=='none');if(!cards.length)return;if(currentCardIdx>=0&&currentCardIdx<cards.length)cards[currentCardIdx].classList.remove('open');const dir=(document.documentElement.dir==='rtl')?(e.key==='ArrowRight'?-1:1):(e.key==='ArrowRight'?1:-1);currentCardIdx=Math.max(0,Math.min(cards.length-1,currentCardIdx+dir));cards[currentCardIdx].classList.add('open');cards[currentCardIdx].scrollIntoView({behavior:'smooth',block:'center'});playSound('click')}})}

function toggleCard(id){const c=document.getElementById(id);if(c){c.classList.toggle('open');playSound('click')}}
function toggleHelp(){document.getElementById('helpPanel').classList.toggle('hidden');playSound('click')}
function toggleDuaPanel(){document.getElementById('duaPanel').classList.toggle('hidden');playSound('click')}
function showToast(msg){const t=document.getElementById('toast');const m=document.getElementById('toastMsg');if(t&&m){m.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}}
function initScrollTop(){const b=document.getElementById('scrollTop');window.addEventListener('scroll',()=>{if(b)b.classList.toggle('visible',window.scrollY>300)})}

const AudioCtx=window.AudioContext||window.webkitAudioContext;let audioCtx;
function playSound(type){try{if(!audioCtx)audioCtx=new AudioCtx();const o=audioCtx.createOscillator();const g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);g.gain.value=0.06;if(type==='click'){o.frequency.value=800;o.type='sine';g.gain.value=0.04}else if(type==='success'){o.frequency.value=523;o.type='sine';g.gain.value=0.06}else if(type==='theme'){o.frequency.value=440;o.type='triangle';g.gain.value=0.05}o.start();o.stop(audioCtx.currentTime+0.1)}catch(e){}}
